### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by gilesc** [adaptivegenome/repeatseq#1]
Hi, I run the following sorted BAM (and BAM index) files which were aligned using bowtie2 to hg19.
http://wren.omrf.org/data/repeatseq/SRR057346.bam
http://wren.omrf.org/data/repeatseq/SRR057346.bam.bai

I also used UCSC's hg19 chromFa.zip concatenated into one large hg19.fa file and the provided hg19.max5.regions.

The program runs for about 20 minutes then segfaults. It creates the VCF file and the outputs a header into the VCF file, but no other rows.  If I specify -counts, it does seem to output a complete counts file, but still segfaults.  This is all on 64-bit Ubuntu compiled with g++ 4.6.1.

Also a few other miscellaneous things:
- The program fails with a cryptic error unless an appropriate BAM index file is present.
- The README refers to PDF documentation but I could not find any in the repository or on Mittelman lab web site. It would be especially nice to know what exactly the .counts file contains.

Thanks!

**Comment by gilesc** [comment]
EDIT:

Also, in trying to debug this problem, I added vcf.flush() immediately after the line 801:
vGT.erase( tempgt );
This reveals that the crash occurs in the middle of chromosome 6 (the VCF file fills with some rows until chr6).

Also, here is a core dump:
http://wren.omrf.org/data/repeatseq/repeatseq.core

**Comment by adaptivegenome** [comment]
Thanks for the bug report. We will take a look. Can you also post the last region or position on chromosome 6 that is reported in the VCF. It will help narrow down the offending region. Also we use the human hg19 reference from the Broad and I am not sure if that is going to be a different file or not. Either way, we will sort it out.

**Comment by gilesc** [comment]
Here's the VCF:
http://wren.omrf.org/data/repeatseq/SRR057346.bam.vcf

**Comment by ghost** [comment]
Hi Cory,

The repeat that's causing the problem is chr6:133135718-133135727 and the problem is that there are too many reads in the bam file that overlap these 10 bases: both repeatseq and 'samtools view' are reporting 123,002 reads for the region.

Were you expecting this many reads in one spot? Let me know if you're seeing something different.

Repeatseq can't handle this high of a density as it would cause issues with a few of the data structures used, but we can look into adding more graceful handling of these sorts of extreme cases.

For your other two notes, thanks. I think you're referring to the '.calls' file, here is the description from the the documentation which should be posted soon:

The .calls format is tab delimited and contains each genotype and minimal additional information. The genotype field is “NA” when a genotype is unable to be determined, “N” if the genotype is homozygous with length N, or “NhM” if the genotype is heterozygous with lengths N and M. Similar to the QUAL field in the VCF format, the confidence field here is the phred-scaled quality score for the assertion made in the genotype field, i.e. it gives the value of -10log_10(p_incorrect-call); high values indicate high confidence calls.

Example:
[region]                 [TRF string]                                            [Genotype]     [Confidence]
2L:6146-6162      1_7.0_1_100_0_14_0_0_0_100_0.00_T              17            39.3627
2L:7006-7017      5_3.8_4_78_21_20_52_0_0_47_1.00_ATTA         NA            NA
2L:10589-10595      3_4.0_3_100_0_24_66_0_0_33_0.92_AAT          7h6      17.5857
